arch:
  A_cycles: 2
  A_layers: 2
  B_layers: 2
  B_per_A: 1
  C_every_A: 2
  C_layers: 2
  M_layers: 2
  M_per_B: 2
  beta_fast: 32
  beta_slow: 1
  compile_modules: false
  disable_c_read_in_b: false
  ego_token: true
  expansion: 4
  expert_capacity_factor: 1.25
  freeze_c_writes: false
  halt_exploration_prob: 0.1
  halt_max_steps: 8
  hidden_size: 512
  kv_lora_rank: 256
  loss:
    loss_type: stablemax_cross_entropy
    name: losses@ACTLossHead
  mscale: 1.0
  mtp_gamma: 0.5
  mtp_num_future: 0
  n_activated_experts: 4
  n_expert_groups: 1
  n_limited_groups: 1
  n_routed_experts: 16
  name: hrm.hrm_4l_act_v3@HierarchicalReasoningModel4L_ACTV3
  num_chitta_slots: 8
  num_heads: 8
  num_plan_tokens: 0
  original_seq_len: 512
  pos_encodings: rope
  puzzle_emb_ndim: 512
  q_lora_rank: 0
  qk_nope_head_dim: 64
  qk_rope_head_dim: 32
  rms_norm_eps: 1.0e-05
  rope_factor: 1.0
  rope_theta: 10000.0
  route_scale: 1.0
  router_noise_std: 0.0
  router_temperature: 1.0
  use_film: false
  use_moe: false
  use_parallel_embedding: false
  v_head_dim: 64
beta1: 0.9
beta2: 0.95
checkpoint_every_eval: true
checkpoint_path: checkpointnew
data_path: data/sudoku-quick-test
epochs: 300
eval_interval: 50
eval_save_outputs: []
global_batch_size: 32
lr: 0.0001
lr_min_ratio: 0.1
lr_warmup_steps: 1000
project_name: Sudoku-quick-test ACT-torch
puzzle_emb_lr: 0.0001
puzzle_emb_weight_decay: 0.1
run_name: HierarchicalReasoningModel4L_ACTV3 crazy-tuna
seed: 0
weight_decay: 0.01
